language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements-dev.txt

script:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python -m unittest discover; fi